### ISSUE TITLE
key_words2.txt

### ISSUE THREAD

**Issue by Lsj425** [HUANGZHIHAO1994/weibo-analysis-and-visualization#1]
请问LDA.py里的key_words2.txt是怎么来的

**Comment by ToJ112** [comment]
同问

**Comment by Verasince1997** [comment]
> 请问LDA.py里的key_words2.txt是怎么来的

请问朋友 Senti_Keyword_total_id.csv在哪生成 是不是senti_analy.py Senti_Keyword_total_id.csv和Senti_Keyword_total.csv不同在哪呢 weibo_id么 谢谢

**Comment by HUANGZHIHAO1994** [comment]
key_words2.txt是自己写的 应该是以Senti_Keyword_total.csv为准，Senti_Keyword_total_id.csv应该就是Senti_Keyword_total.csv增加了一列weibo_id（可能当时写的时候版本没统一，目前这里没有生成Senti_Keyword_total_id.csv），反正那一列也会被drop，在3Dbar.py，lines.py，pie.py等py文件中用Senti_Keyword_total.csv，并删除drop中weibo_id即可
