### ISSUE TITLE
Senti_Keyword_total_id.csv没有程序会生成 作者是怎么生成的？

### ISSUE THREAD

**Issue by Verasince1997** [HUANGZHIHAO1994/weibo-analysis-and-visualization#3]
这个csv文件应该是senti_analy.py中output的 是不是那儿写忘了 我只有自己深入了解下代码 找出Senti_Keyword_total_id.csv与Senti_Keyword_total.csv的不同

**Comment by HUANGZHIHAO1994** [comment]
应该是以Senti_Keyword_total.csv，Senti_Keyword_total_id.csv应该就是Senti_Keyword_total.csv增加了一列weibo_id（可能当时写的时候版本没统一，目前这里没有生成Senti_Keyword_total_id.csv），反正那一列也会被drop，在3Dbar.py，lines.py，pie.py等py文件中用Senti_Keyword_total.csv，并删除drop中weibo_id即可
